// export { default as common } from './common';
// export { default as red } from './red';
// export { default as pink } from './pink';
// export { default as purple } from './purple';
// export { default as deepPurple } from './deepPurple';
// export { default as indigo } from './indigo';
// export { default as blue } from './blue';
// export { default as lightBlue } from './lightBlue';
// export { default as cyan } from './cyan';
// export { default as teal } from './teal';
// export { default as green } from './green';
// export { default as lightGreen } from './lightGreen';
// export { default as lime } from './lime';
// export { default as yellow } from './yellow';
// export { default as amber } from './amber';
// export { default as orange } from './orange';
// export { default as deepOrange } from './deepOrange';
// export { default as brown } from './brown';
// export { default as grey } from './grey';
// export { default as blueGrey } from './blueGrey';

export {default as amber} from '@mui/material/colors/amber.js';
export {default as blue} from '@mui/material/colors/blue.js';
export {default as blueGrey} from '@mui/material/colors/blueGrey.js';
export {default as brown} from '@mui/material/colors/brown.js';
export {default as common} from '@mui/material/colors/common.js';
export {default as cyan} from '@mui/material/colors/cyan.js';
export {default as deepOrange} from '@mui/material/colors/deepOrange.js';
export {default as deepPurple} from '@mui/material/colors/deepPurple.js';
export {default as green} from '@mui/material/colors/green.js';
export {default as grey} from '@mui/material/colors/grey.js';
export {default as indigo} from '@mui/material/colors/indigo.js';
export {default as lightBlue} from '@mui/material/colors/lightBlue.js';
export {default as lightGreen} from '@mui/material/colors/lightGreen.js';
export {default as lime} from '@mui/material/colors/lime.js';
export {default as orange} from '@mui/material/colors/orange.js';
export {default as pink} from '@mui/material/colors/pink.js';
export {default as purple} from '@mui/material/colors/purple.js';
export {default as red} from '@mui/material/colors/red.js';
export {default as teal} from '@mui/material/colors/teal.js';
export {default as yellow} from '@mui/material/colors/yellow.js';
